version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_zapatillas
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_zapatillas"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: ecommerce_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  web:
    image: node:20-alpine
    container_name: ecommerce_web
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      HOST: "0.0.0.0"
      PORT: "5173"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/ecommerce_zapatillas"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

volumes:
  db_data:
  minio_data:
